name: Build Project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Cache CMake and build dependencies
      - name: Cache CMake
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/CMake
            build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          spectre: true

      - name: Set Up Build Directory
        run: |
          rm -rf build || true
          mkdir build

      - name: Install Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build \
            libasound2-dev libjack-jackd2-dev ladspa-sdk \
            libcurl4-openssl-dev libfreetype-dev libfontconfig1-dev \
            libx11-dev libxcomposite-dev libxcursor-dev libxext-dev \
            libxinerama-dev libxrandr-dev libxrender-dev \
            libwebkit2gtk-4.1-dev libglu1-mesa-dev mesa-common-dev
        shell: bash
        # Use a similar conditional block for Mac and Windows if necessary

      - name: Configure Build
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cmake --preset "Windows Release"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cmake --preset "Mac Release" -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cmake --preset "Linux Release"
          fi

      - name: Build
        run: cmake --build build --config "Release"

      - name: Package Artifacts
        run: |
          mkdir -p artifacts
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp -r build/src/DisfluxPlugin_artefacts/Release/VST3 artifacts/
            cp -r build/src/DisfluxPlugin_artefacts/Release/CLAP artifacts/
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp -r build/src/DisfluxPlugin_artefacts/Release/VST3 artifacts/
            cp -r build/src/DisfluxPlugin_artefacts/Release/CLAP artifacts/
            cp -r build/src/DisfluxPlugin_artefacts/Release/AU artifacts/
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cp -r build/src/DisfluxPlugin_artefacts/Release/VST3 artifacts/
            cp -r build/src/DisfluxPlugin_artefacts/Release/LV2 artifacts/
            cp -r build/src/DisfluxPlugin_artefacts/Release/CLAP artifacts/
          fi
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: artifacts
