#===========================================================================================
# This workflow will build the project for Windows, macOS, and Linux.
# It will also build an Arch Linux and Fedora package using Docker containers.
# The artifacts will be uploaded to the release page.
#
# TODO:
# - Add a step to sign the macOS package
# - Add a step after release to update the AUR repository
#===========================================================================================

name: Build Project
on:
  workflow_dispatch:
  pull_request:
  push:
defaults:
  run:
    shell: bash
#===========================================================================================
# Environment Variables

env:
  PROJECT_NAME: Disflux
  BUNDLE_ID: com.dimethoxy.disflux
  VERSION: 0.1.0

#===========================================================================================
# Build Jobs
#===========================================================================================
jobs:
  #=========================================================================================
  # Windows Build
  #=========================================================================================
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          spectre: true

      - name: Set Up Windows
        run: |
          choco install ninja
          choco install innosetup

      - name: Select CMake Preset
        run: cmake --preset "Windows Release"

      - name: Build
        run: cmake --build build --config "Release"

      - name: Copy Build Artifacts
        run: |
          BUILD_DIR="build/src/${{env.PROJECT_NAME}}Plugin_artefacts/Release"
          mkdir -p artifacts
          cp -r $BUILD_DIR/VST3/${{env.PROJECT_NAME}}.vst3 artifacts/
          cp -r $BUILD_DIR/CLAP/${{env.PROJECT_NAME}}.clap artifacts/
        shell: bash

      - name: Create Installer
        run: |
          PACKAGE_NAME="${{env.PROJECT_NAME}}-Snapshot-Windows.exe"
          mkdir -p packaging

          envsubst < pkg/windows/Setup.iss > packaging/Setup.iss
          iscc packaging/Setup.iss

          mv "${{env.PROJECT_NAME}}-Setup.exe" artifacts/$PACKAGE_NAME
        shell: bash

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-windows
          path: artifacts

  #=========================================================================================
  # macOS Build
  #=========================================================================================
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Mac
        run: brew install ninja osxutils

      - name: Select CMake Preset
        run: cmake --preset "Mac Release" -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"

      - name: Build
        run: cmake --build build --config "Release"

      - name: Copy Build Artifacts
        run: |
          BUILD_DIR="build/src/${{env.PROJECT_NAME}}Plugin_artefacts/Release"
          mkdir -p artifacts
          cp -r $BUILD_DIR/VST3/${{env.PROJECT_NAME}}.vst3 artifacts/
          cp -r $BUILD_DIR/CLAP/${{env.PROJECT_NAME}}.clap artifacts/
          cp -r $BUILD_DIR/AU/${{env.PROJECT_NAME}}.component artifacts/
          cd artifacts 
          ls -la
        shell: bash

      - name: Import Certificates
        uses: sudara/basic-macos-keychain-action@v1
        id: keychain
        with:
          dev-id-app-cert: ${{ secrets.DEV_ID_APP_CERT }}
          dev-id-app-password: ${{ secrets.DEV_ID_PASSWORD }}
          dev-id-installer-cert: ${{ secrets.DEV_ID_INSTALL_CERT }}
          dev-id-installer-password: ${{ secrets.DEV_ID_PASSWORD }}

      - name: Codesign (macOS)
        run: |
          VST3_BIN="artifacts/{{env.PROJECT_NAME}}.vst3/Contents/MacOS/{{env.PROJECT_NAME}}"
          CLAP_BIN="artifacts/{{env.PROJECT_NAME}}.clap/Contents/MacOS/{{env.PROJECT_NAME}}"
          AU_BIN="artifacts/{{env.PROJECT_NAME}}.component/Contents/MacOS/{{env.PROJECT_NAME}"

          codesign \
            --force -s "${{ secrets.DEVELOPER_ID_APPLICATION}}" \
            -v "$VST3_BIN" 
            --deep --strict --options=runtime --timestamp

          codesign \
            --force -s "${{ secrets.DEVELOPER_ID_APPLICATION}}" \
            -v "$CLAP_BIN" \ 
            --deep --strict --options=runtime --timestamp

          codesign \
            --force -s "${{ secrets.DEVELOPER_ID_APPLICATION}}" \
            -v "$AU_BIN" \
            --deep --strict --options=runtime --timestamp

        shell: bash

      - name: Create Installer
        run: |
          VST3_PATH="artifacts/Disflux.vst3"
          CLAP_PATH="artifacts/Disflux.clap"
          AU_PATH="artifacts/Disflux.component"

          mkdir -p packaging
          envsubst < pkg/mac/distribution.xml > packaging/distribution.xml

          pkgbuild \
            --identifier "${{ env.BUNDLE_ID }}.vst3.pkg" \
            --version "$VERSION" \
            --component "$VST3_PATH" \
            --install-location "/Library/Audio/Plug-Ins/VST3" \
            "packaging/${{env.PROJECT_NAME}}.vst3.pkg"

          pkgbuild \
            --identifier "${{ env.BUNDLE_ID }}.clap.pkg" \
            --version "$VERSION" \
            --component "$CLAP_PATH" \
            --install-location "/Library/Audio/Plug-Ins/CLAP" \
            "packaging/${{env.PROJECT_NAME}}.clap.pkg"

          pkgbuild \
            --identifier "${{ env.BUNDLE_ID }}.au.pkg" \
            --version "$VERSION" \
            --component "$AU_PATH" \
            --install-location "/Library/Audio/Plug-Ins/Components" \
            "packaging/${{env.PROJECT_NAME}}.au.pkg"

          cd packaging
          productbuild \
            --resources ./resources \
            --distribution distribution.xml \
            --sign "${{ secrets.DEVELOPER_ID_INSTALLER }}" \
            --timestamp "${{env.PROJECT_NAME}}.pkg"

          xcrun notarytool submit "${{env.PROJECT_NAME}}.pkg" \
            --apple-id ${{ secrets.NOTARIZATION_USERNAME }} \
            --password ${{ secrets.NOTARIZATION_PASSWORD }} \
            --team-id ${{ secrets.TEAM_ID }} 
            --wait

          xcrun stapler staple "${{env.PROJECT_NAME}}.pkg"
          mv "${{env.PROJECT_NAME}}.pkg" ../artifacts/
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-macos
          path: artifacts

  #=========================================================================================
  # Ubuntu Linux Build
  #=========================================================================================
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Linux
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
          sudo apt install libasound2-dev \
                           libjack-jackd2-dev \
                           ladspa-sdk \
                           libcurl4-openssl-dev  \
                           libfreetype-dev \
                           libfontconfig1-dev \
                           libx11-dev \
                           libxcomposite-dev \
                           libxcursor-dev \
                           libxext-dev \
                           libxinerama-dev \
                           libxrandr-dev \
                           libxrender-dev \
                           libwebkit2gtk-4.1-dev \
                           libglu1-mesa-dev mesa-common-dev
          sudo apt-get install -y dpkg-dev devscripts
          sudo /usr/bin/Xvfb $DISPLAY &
        shell: bash

      - name: Select CMake Preset
        run: cmake --preset "Linux Release"

      - name: Build
        run: cmake --build build --config "Release"

      - name: Package Linux Artifacts
        run: |
          # Define variables
          ARTIFACTS_DIR="artifacts"
          BUILD_DIR="build/src/DisfluxPlugin_artefacts/Release"
          DEBIAN_PACKAGE_DIR="disflux-snapshot-linux-ubuntu"
          DEBIAN_CONTROL_FILE="pkg/ubuntu/control"
          CLAP_DIR="/usr/lib/clap/Disflux"
          LV2_DIR="/usr/lib/lv2/Disflux"
          VST3_DIR="/usr/lib/vst3/Disflux"

          # Prepare artifacts directory
          mkdir -p $ARTIFACTS_DIR

          # Prepare Debian package directory structure
          mkdir -p $DEBIAN_PACKAGE_DIR/DEBIAN
          mkdir -p $DEBIAN_PACKAGE_DIR/$CLAP_DIR
          mkdir -p $DEBIAN_PACKAGE_DIR/$LV2_DIR
          mkdir -p $DEBIAN_PACKAGE_DIR/$VST3_DIR

          # Copy files to Debian package directory
          cp -r $BUILD_DIR/CLAP/Disflux.clap \
                $DEBIAN_PACKAGE_DIR/$CLAP_DIR/
          cp -r $BUILD_DIR/LV2/Disflux.lv2 \
                $DEBIAN_PACKAGE_DIR/$LV2_DIR/
          cp -r $BUILD_DIR/VST3/Disflux.vst3 \
                $DEBIAN_PACKAGE_DIR/$VST3_DIR/

          # Copy vanilla files to artifacts directory
          cp -r $BUILD_DIR/LV2/Disflux.lv2 \
                $ARTIFACTS_DIR/
          cp -r $BUILD_DIR/CLAP/Disflux.clap \
                $ARTIFACTS_DIR/
          cp -r $BUILD_DIR/VST3/Disflux.vst3 \
                $ARTIFACTS_DIR/

          # Copy control file to Debian package directory
          cp $DEBIAN_CONTROL_FILE $DEBIAN_PACKAGE_DIR/DEBIAN

          # Build Debian package
          dpkg-deb --build $DEBIAN_PACKAGE_DIR

          # Move Debian package to artifacts
          cp -r $DEBIAN_PACKAGE_DIR.deb $ARTIFACTS_DIR/
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-ubuntu
          path: artifacts

  #=========================================================================================
  # Arch Linux Build
  #=========================================================================================
  build-archlinux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install Base Packages
        run: |
          pacman -Sy --noconfirm base-devel git

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create user for build process
        run: |
          useradd -m dimethoxy
          sudo su - dimethoxy

      - name: Set permissions for the build directory
        run: |
          sudo chown -R dimethoxy:dimethoxy /__w/Disflux/Disflux/pkg/arch/git
          sudo chmod -R u+rw /__w/Disflux/Disflux/pkg/arch/git

      - name: Disable sudo password prompt
        run: |
          echo 'dimethoxy ALL=(ALL) NOPASSWD: ALL' | sudo tee -a /etc/sudoers

      - name: Build Package
        run: |
          sudo -u dimethoxy bash -c 'cd pkg/arch/git && makepkg -s --noconfirm'

      - name: Package Artifacts
        run: |
          # Remove the default package
          rm pkg/arch/git/*debug*.pkg.tar.zst

          # Move the package to the root directory
          mv pkg/arch/git/*.pkg.tar.zst .

          # Rename the package
          mv *.pkg.tar.zst disflux-snapshot-linux-arch.pkg.tar.zst

          # Move the package to the artifacts directory
          mkdir -p artifacts
          mv disflux-snapshot-linux-arch.pkg.tar.zst artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-archlinux
          path: artifacts

  #=========================================================================================
  # Release the project
  #=========================================================================================
  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-ubuntu, build-archlinux]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Artifacts
        uses: actions/download-artifact@v4

      - name: Package Artifacts
        run: |
          mv artifacts-windows/*.exe .
          mv artifacts-macos/*.pkg .

          # Move the Arch package to the root directory
          mv build-artifacts-archlinux/disflux-snapshot-linux-arch.pkg.tar.zst .

          # Move the deb package to the root directory
          mv build-artifacts-ubuntu/disflux-snapshot-linux-ubuntu.deb .

          # Zip the artifacts
          zip -r disflux-snapshot-linux-vanilla.zip ./build-artifacts-ubuntu
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Snapshot"
          prerelease: true
          body: |
            ### ⚠️ WARNING: Unstable Release ⚠️
            This is a **unstable** snapshot intended solely for testing purposes.
            It may contain bugs, incomplete features, or cause instability.
            **Not recommended** for production or general use—proceed with caution.

      - name: Upload Artifacts
        run: |
          gh release upload "Snapshot" ${{env.PROJECT_NAME}}-Snapshot-Windows.exe --clobber
          gh release upload "Snapshot" disflux-snapshot-linux-arch.pkg.tar.zst --clobber
          gh release upload "Snapshot" disflux-snapshot-linux-ubuntu.deb --clobber
          gh release upload "Snapshot" disflux-snapshot-linux-vanilla.zip --clobber
          gh release upload "Snapshot" disflux-snapshot-macos.pkg --clobber
