name: Build Project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache CMake dependency source code
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake-dependency-sources
        with:
          path: ${{github.workspace}}/build/_deps/*-src
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Cache CMake dependency build objects
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake-dependency-builds
        with:
          path: |
            ${{github.workspace}}/build/_deps/*-build
            ${{github.workspace}}/build/_deps/*-subbuild
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cxx }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cxx }}-

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          spectre: true

      - name: Set Up Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install ninja -y || exit 0
        shell: pwsh

      - name: Set Up Mac
        if: matrix.os == 'macos-latest'
        run: |
          brew install ninja || true
        shell: bash

      - name: Set Up Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          sudo apt-get install -y \
            libasound2-dev libjack-jackd2-dev ladspa-sdk \
            libcurl4-openssl-dev libfreetype-dev libfontconfig1-dev \
            libx11-dev libxcomposite-dev libxcursor-dev libxext-dev \
            libxinerama-dev libxrandr-dev libxrender-dev \
            libwebkit2gtk-4.1-dev libglu1-mesa-dev mesa-common-dev
        shell: bash

      - name: Configure Build on Windows
        if: matrix.os == 'windows-latest'
        run: cmake --preset "Windows Release"

      - name: Configure Build on macOS
        if: matrix.os == 'macos-latest'
        run: cmake --preset "Mac Release" -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"

      - name: Configure Build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: cmake --preset "Linux Release"

      - name: Build
        run: cmake --build build --config "Release"

      - name: Package Windows Artifacts
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p artifacts
          cp -r build/src/DisfluxPlugin_artefacts/Release/VST3 artifacts/
          cp -r build/src/DisfluxPlugin_artefacts/Release/CLAP artifacts/
        shell: bash

      - name: Package macOS Artifacts
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p artifacts
          cp -r build/src/DisfluxPlugin_artefacts/Release/VST3 artifacts/
          cp -r build/src/DisfluxPlugin_artefacts/Release/CLAP artifacts/
          cp -r build/src/DisfluxPlugin_artefacts/Release/AU artifacts/
        shell: bash

      - name: Package Linux Artifacts
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p artifacts
          cp -r build/src/DisfluxPlugin_artefacts/Release/VST3 artifacts/
          cp -r build/src/DisfluxPlugin_artefacts/Release/LV2 artifacts/
          cp -r build/src/DisfluxPlugin_artefacts/Release/CLAP artifacts/
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: artifacts
